### ISSUE TITLE
unusable

### ISSUE THREAD

**Issue by CloverLL** [snicoll-demos/demo-animated-banner#3]
.*:::**.                               
                                 :::::::::::::::::::       .                  
                              *::::::::::::::::::::::::   *:                  
                            :::::::::::::::::::::::::::::: .*                 
                          *:::::::::::::::::::::::::::::*   :                 
                         *::::::::::::::::::::::::::::       *                
                     *:::::::* ::::::::::::::::::::          :                
                 *::::::::::::::::::::::::**.                ..               
               ::::::::::::::::::.                            :::             
             ::::::::::::::::::                         :     ::::::          
            :::::::::::::::::.                         :      :::::::*        
            :::::::::::::::::                        ::       ::::::::*       
           *::::::::::::::::                       ::        .:::::::::.      
           :::::::::::::::::                    *::.         :::::::::::      
           .:::::::::::::::::               .::::           ::::::::::::      
            :::::::::::::::::.          *::::::            ::::::::::::*      
            .:::::::::::::::::::::::::::::.              ::::::::::::::       
              ::::::::::::::*  .::::                *:::::::::::::::::.       
               *:::::::::::::  ::::::::::::::::::::::::::::::::::::::         
                  :::::::::::::::::::::::::::::::::::::::::::::::::.          
                      .*::::::::::::::::::::::::::::::::::::::*.

**Comment by snicoll** [comment]
Thanks for the feedback.
